general {
    col.active_border = rgba(9e8e8277)
    col.inactive_border = rgba(51443a55)
}

misc {
    background_color = rgba(19120cFF)
}


windowrule = border_color rgba(ffb878AA) rgba(ffb87877), match:pin 1
