-- Generated by Quickshell PeripheralSettings.qml. Do not edit manually.
hl.config({ input = { accel_profile = "flat", follow_mouse = 1, left_handed = false, numlock_by_default = true, scroll_factor = 1, sensitivity = -0.87, touchpad = { disable_while_typing = true, drag_lock = false, natural_scroll = true, scroll_factor = 0.5, tap_and_drag = true, tap_to_click = true } } })
