pragma Singleton

import QtQuick

QtObject {
    readonly property var entries: [
        { label: "Wallpaper & Colors", page: 5, subTab: 1, icon: "tune" },
        { label: "Color palette style", page: 5, subTab: 1, icon: "tune" },
        { label: "Transparency", page: 5, subTab: 1, icon: "tune" },
        { label: "Screen rounded corners", page: 5, subTab: 1, icon: "tune" },
        { label: "GTK theme", page: 5, subTab: 1, icon: "palette" },
        { label: "Icon theme", page: 5, subTab: 1, icon: "palette" },
        { label: "Cursor theme", page: 5, subTab: 1, icon: "palette" },
        { label: "Cursor size", page: 5, subTab: 1, icon: "palette" },
        { label: "Font family", page: 5, subTab: 1, icon: "palette" },
        { label: "Font size", page: 5, subTab: 1, icon: "palette" },
        { label: "Change wallpaper", page: 5, subTab: 1, icon: "palette" },
        { label: "Dark mode", page: 5, subTab: 1, icon: "palette" },
        { label: "Light mode", page: 5, subTab: 1, icon: "palette" },
        { label: "Color scheme", page: 5, subTab: 1, icon: "palette" },
        { label: "Kvantum theme", page: 5, subTab: 1, icon: "palette" },
        { label: "KDE theme", page: 5, subTab: 1, icon: "palette" },
        { label: "GNOME interface settings", page: 5, subTab: 1, icon: "palette" },
        { label: "GTK 3 settings", page: 5, subTab: 1, icon: "palette" },
        { label: "GTK 4 settings", page: 5, subTab: 1, icon: "palette" },
        { label: "kdeglobals", page: 5, subTab: 1, icon: "palette" },
        { label: "Prefer dark apps", page: 5, subTab: 1, icon: "palette" },
        { label: "Text scaling", page: 5, subTab: 1, icon: "palette" },
        { label: "Hot corners", page: 5, subTab: 1, icon: "palette" },
        { label: "Animations", page: 5, subTab: 1, icon: "palette" },
        { label: "Bluetooth devices", page: 1, subTab: 1, sectionId: "devices", icon: "bluetooth" },
        { label: "Pair device", page: 1, subTab: 1, sectionId: "devices", icon: "bluetooth" },
        { label: "Audio output device", page: 1, subTab: 1, sectionId: "overview", icon: "bluetooth" },
        { label: "Open Bluetooth app", page: 1, subTab: 1, sectionId: "other", icon: "bluetooth" },
        { label: "Night light", page: 3, icon: "desktop_windows" },
        { label: "Color temperature", page: 3, icon: "desktop_windows" },
        { label: "Night light schedule", page: 3, icon: "desktop_windows" },
        { label: "Anti-flashbang", page: 3, icon: "desktop_windows" },
        { label: "Low battery threshold", page: 3, icon: "desktop_windows" },
        { label: "Critical battery threshold", page: 3, icon: "desktop_windows" },
        { label: "Automatic suspend on low battery", page: 3, icon: "desktop_windows" },
        { label: "Monitor positions", page: 3, icon: "desktop_windows" },
        { label: "Brightness", page: 3, icon: "desktop_windows" },
        { label: "Default output device", page: 4, icon: "volume_up" },
        { label: "Default input device", page: 4, icon: "volume_up" },
        { label: "Mono output", page: 4, icon: "volume_up" },
        { label: "App streams", page: 4, icon: "volume_up" },
        { label: "Earbang protection", page: 4, icon: "volume_up" },
        { label: "Volume ceiling", page: 4, icon: "volume_up" },
        { label: "Max volume increase per step", page: 4, icon: "volume_up" },
        { label: "System sounds", page: 4, icon: "volume_up" },
        { label: "Battery alert sound", page: 4, icon: "volume_up" },
        { label: "Microphone input", page: 4, icon: "volume_up" },
        { label: "Wi-Fi networks", page: 1, subTab: 0, sectionId: "networks", icon: "language" },
        { label: "Scan Wi-Fi", page: 1, subTab: 0, sectionId: "networks", icon: "language" },
        { label: "Ethernet", page: 1, subTab: 0, sectionId: "internet", icon: "language" },
        { label: "Network settings", page: 1, subTab: 0, sectionId: "extra", icon: "language" },
        { label: "Captive portal", page: 1, subTab: 0, sectionId: "extra", icon: "language" },
        { label: "Bar", page: 5, subTab: 0, icon: "toolbar" },
        { label: "Bar position", page: 5, subTab: 0, icon: "toolbar" },
        { label: "Bar style", page: 5, subTab: 0, icon: "toolbar" },
        { label: "Bar transparency", page: 5, subTab: 0, icon: "toolbar" },
        { label: "Utility buttons", page: 5, subTab: 0, icon: "toolbar" },
        { label: "Workspaces", page: 5, subTab: 0, icon: "toolbar" },
        { label: "Tooltips", page: 5, subTab: 0, icon: "toolbar" },
        { label: "Dock", page: 5, subTab: 0, icon: "preview" },
        { label: "Dock pinned apps", page: 5, subTab: 0, icon: "preview" },
        { label: "Left sidebar", page: 5, subTab: 0, icon: "left_panel_open" },
        { label: "Right sidebar", page: 5, subTab: 0, icon: "right_panel_open" },
        { label: "Corner open sidebar", page: 5, subTab: 0, icon: "left_panel_open" },
        { label: "Quick toggles layout", page: 5, subTab: 0, icon: "right_panel_open" },
        { label: "Translator sidebar", page: 5, subTab: 0, icon: "left_panel_open" },
        { label: "Cheat sheet super key symbol", page: 5, subTab: 0, icon: "preview" },
        { label: "Lock screen", page: 5, subTab: 0, icon: "preview" },
        { label: "Auto-lock delay", page: 5, subTab: 0, icon: "preview" },
        { label: "Lock screen style", page: 5, subTab: 0, icon: "preview" },
        { label: "Require password to power off", page: 5, subTab: 0, icon: "preview" },
        { label: "Notifications timeout", page: 5, subTab: 0, icon: "preview" },
        { label: "Crosshair overlay", page: 5, subTab: 0, icon: "preview" },
        { label: "Floating image overlay", page: 5, subTab: 0, icon: "preview" },
        { label: "Overview layout", page: 5, subTab: 0, icon: "preview" },
        { label: "Main font", page: 5, subTab: 0, icon: "preview" },
        { label: "Monospace font", page: 5, subTab: 0, icon: "preview" },
        { label: "Numbers font", page: 5, subTab: 0, icon: "preview" },
        { label: "On-screen display timeout", page: 5, subTab: 0, icon: "preview" },
        { label: "Region selector / screen snip", page: 5, subTab: 0, icon: "preview" },
        { label: "Wallpaper file picker", page: 5, subTab: 0, icon: "preview" },
        { label: "Bluetooth app command", page: 5, subTab: 0, icon: "apps" },
        { label: "Network settings command", page: 5, subTab: 0, icon: "apps" },
        { label: "Terminal command", page: 5, subTab: 0, icon: "apps" },
        { label: "System update command", page: 5, subTab: 0, icon: "apps" },
        { label: "Volume mixer command", page: 5, subTab: 0, icon: "apps" },
        { label: "Task manager command", page: 5, subTab: 0, icon: "apps" },
        { label: "Change password command", page: 5, subTab: 0, icon: "apps" },
        { label: "Launcher pinned apps", page: 5, subTab: 0, icon: "apps" },
        { label: "Manage users", page: 6, icon: "person" },
        { label: "Change password", page: 6, icon: "person" },
        { label: "Language / locale", page: 7, icon: "schedule" },
        { label: "System locale", page: 7, icon: "schedule" },
        { label: "Generate translation", page: 7, icon: "schedule" },
        { label: "Clock format 24h 12h", page: 7, icon: "schedule" },
        { label: "Second precision clock", page: 7, icon: "schedule" },
        { label: "Translation map", page: 7, icon: "schedule" },
        { label: "Cursor size", page: 8, icon: "accessibility_new" },
        { label: "Text scaling accessibility", page: 8, icon: "accessibility_new" },
        { label: "Disable animations", page: 8, icon: "accessibility_new" },
        { label: "Readability", page: 8, icon: "accessibility_new" },
        { label: "AI policy", page: 9, icon: "shield_lock" },
        { label: "Clipboard privacy", page: 9, icon: "shield_lock" },
        { label: "Wallpaper privacy", page: 9, icon: "shield_lock" },
        { label: "Check for updates", page: 10, icon: "system_update" },
        { label: "System information", page: 10, icon: "system_update" },
        { label: "CPU memory GPU info", page: 10, icon: "system_update" },
        { label: "AI system prompt", page: 11, icon: "widgets" },
        { label: "Music recognition timeout", page: 11, icon: "widgets" },
        { label: "User agent", page: 11, icon: "widgets" },
        { label: "Search engine URL", page: 11, icon: "widgets" },
        { label: "Search prefixes", page: 11, icon: "widgets" },
        { label: "Weather city GPS", page: 11, icon: "widgets" },
        { label: "Screenshot save path", page: 11, icon: "widgets" },
        { label: "Video recording path", page: 11, icon: "widgets" },
        { label: "Hyprland config files", page: 12, icon: "deployed_code" },
        { label: "Keybinds", page: 12, icon: "deployed_code" },
        { label: "Window rules", page: 12, icon: "deployed_code" },
        { label: "Workspace bindings", page: 12, icon: "deployed_code" },
        { label: "Monitor overrides", page: 12, icon: "deployed_code" },
        { label: "Environment variables", page: 12, icon: "deployed_code" },
        { label: "Startup commands autostart", page: 12, icon: "deployed_code" },
        { label: "Mouse sensitivity", page: 2, icon: "mouse" },
        { label: "Mouse acceleration profile", page: 2, icon: "mouse" },
        { label: "Mouse wheel speed", page: 2, icon: "mouse" },
        { label: "Follow mouse focus", page: 2, icon: "mouse" },
        { label: "Left-handed mouse", page: 2, icon: "mouse" },
        { label: "Touchpad natural scroll", page: 2, icon: "touchpad_mouse" },
        { label: "Tap to click", page: 2, icon: "touchpad_mouse" },
        { label: "Tap and drag", page: 2, icon: "touchpad_mouse" },
        { label: "Disable touchpad while typing", page: 2, icon: "touchpad_mouse" },
        { label: "Touchpad scroll factor", page: 2, icon: "touchpad_mouse" },
        { label: "Keyboard numlock", page: 2, icon: "keyboard" },
        { label: "Quickshell scroll tuning", page: 2, icon: "tune" },
        { label: "Detected input devices", page: 2, icon: "devices" },
    ]
}
