#!/usr/bin/env python3
"""Bridge Quickshell's generated palette to Flea's Omarchy theme files.

Python 3.11+; standard library only. Generated state is deliberately not stored
in the dotfiles repository. --check/--dry-run validate without writing anything.
"""

import argparse
import fcntl
import json
import os
from pathlib import Path
import re
import stat
import sys
import tempfile
import tomllib


OWNER_FILE = ".quickshell-theme-bridge"
OWNER = "quickshell-omarchy-theme-bridge-v1\n"
THEME_NAME = "Quickshell\n"
HEX_COLOR = re.compile(r"#[0-9a-fA-F]{6}\Z")
HEADER = "# Generated by omarchy-apps/sync-theme.py; edit the source palette/config.\n"


def rgb(value, label):
    if not isinstance(value, str) or not HEX_COLOR.fullmatch(value):
        raise ValueError(f"{label} must be a six-digit RGB colour, for example #a6e3a1")
    return value.lower()


def render(palette, config):
    """Return complete file bodies, rejecting partial or malformed palettes."""
    if not isinstance(palette, dict):
        raise ValueError("source palette must be a JSON object")
    if not isinstance(config, dict) or set(config) - {"font", "palette"}:
        raise ValueError("theme config only supports [font] and [palette]")
    font = config.get("font", {})
    fallbacks = config.get("palette", {})
    if not isinstance(font, dict) or set(font) - {"base-size"}:
        raise ValueError("[font] only supports base-size")
    if not isinstance(fallbacks, dict) or set(fallbacks) - {"green"}:
        raise ValueError("[palette] only supports green")
    base_size = font.get("base-size", 14)
    if type(base_size) is not int or not 8 <= base_size <= 32:
        raise ValueError("font base-size must be an integer from 8 to 32")
    green = rgb(fallbacks.get("green", "#a6e3a1"), "fallback green")

    def source(*keys):
        for key in keys:
            if key in palette:
                return rgb(palette[key], f"palette {key}")
        raise ValueError(f"source palette is missing {' or '.join(keys)}")

    colors = {
        "background": source("background"),
        "foreground": source("on_surface", "on_background"),
        "accent": source("primary"),
        "muted": source("on_surface_variant"),
        "red": source("error"),
        "dark_background": source("surface_container_low"),
        "cyan": source("tertiary"),
        "green": source("green") if "green" in palette else green,
    }
    # Both official Commons and Flea understand these ANSI aliases.
    colors.update(color1=colors["red"], color2=colors["green"], color6=colors["cyan"])
    colors_body = HEADER + "".join(f'{key} = "{value}"\n' for key, value in colors.items())
    shell_body = HEADER + f"[font]\nbase-size = {base_size}\n"
    return {"colors.toml": colors_body, "shell.toml": shell_body}


def ensure_plain_path(path, directory=False):
    """Never follow theme links, including an Omarchy-managed theme symlink."""
    for parent in reversed(path.parents):
        if parent.is_symlink():
            raise ValueError(f"refusing symlink in output path: {parent}")
    try:
        mode = path.lstat().st_mode
    except FileNotFoundError:
        return
    expected = stat.S_ISDIR(mode) if directory else stat.S_ISREG(mode)
    if not expected:
        raise ValueError(f"refusing non-{'directory' if directory else 'regular file'}: {path}")


def validate_ownership(state_dir):
    ensure_plain_path(state_dir, directory=True)
    theme_dir = state_dir / "theme"
    ensure_plain_path(theme_dir, directory=True)
    for path in (theme_dir / OWNER_FILE, theme_dir / "colors.toml",
                 theme_dir / "shell.toml", state_dir / "theme.name",
                 state_dir / ".quickshell-theme-bridge.lock"):
        ensure_plain_path(path)
    if theme_dir.exists():
        marker = theme_dir / OWNER_FILE
        if not marker.exists() or marker.read_text() != OWNER:
            raise ValueError(f"refusing existing theme not owned by this bridge: {theme_dir}")
    elif (state_dir / "theme.name").exists():
        raise ValueError("refusing existing theme.name without a bridge-owned theme")
    name = state_dir / "theme.name"
    if name.exists() and name.read_text() != THEME_NAME:
        raise ValueError(f"refusing theme.name changed by another theme manager: {name}")


def changed_files(state_dir, rendered):
    return [name for name, body in rendered.items()
            if not (state_dir / "theme" / name).exists()
            or (state_dir / "theme" / name).read_text() != body]


def atomic_write(path, body):
    """Replace a generated file only after its complete new body is on disk."""
    temporary = None
    try:
        with tempfile.NamedTemporaryFile(mode="w", encoding="utf-8", dir=path.parent,
                                         prefix=f".{path.name}.", delete=False) as stream:
            temporary = Path(stream.name)
            stream.write(body)
            stream.flush()
            os.fsync(stream.fileno())
        os.replace(temporary, path)
    finally:
        if temporary is not None:
            temporary.unlink(missing_ok=True)


def sync(state_dir, rendered, check=False):
    """Return changed filenames; no output paths are created in check mode."""
    state_dir = Path(os.path.abspath(state_dir))
    validate_ownership(state_dir)
    if check:
        return changed_files(state_dir, rendered)

    state_dir.mkdir(parents=True, exist_ok=True)
    lock_path = state_dir / ".quickshell-theme-bridge.lock"
    # Two wallpaper events or a simultaneous launcher must not interleave.
    with lock_path.open("a") as lock:
        fcntl.flock(lock, fcntl.LOCK_EX)
        validate_ownership(state_dir)
        theme_dir = state_dir / "theme"
        if not theme_dir.exists():
            theme_dir.mkdir()
            atomic_write(theme_dir / OWNER_FILE, OWNER)
        changed = changed_files(state_dir, rendered)
        for name in changed:
            atomic_write(theme_dir / name, rendered[name])
        theme_name = state_dir / "theme.name"
        if changed or not theme_name.exists():
            # Flea watches THIS inode, not the replaced palette files. Rewrite
            # in place only AFTER both complete TOML files are available.
            with theme_name.open("w", encoding="utf-8") as stream:
                stream.write(THEME_NAME)
                stream.flush()
                os.fsync(stream.fileno())
        return changed


def main(argv=None):
    home = Path.home()
    state_home = Path(os.environ.get("XDG_STATE_HOME") or home / ".local/state")
    config_home = Path(os.environ.get("XDG_CONFIG_HOME") or home / ".config")
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", type=Path,
                        default=state_home / "quickshell/user/generated/colors.json")
    # Flea v0.2.0 uses this fixed location, independently of XDG_STATE_HOME.
    parser.add_argument("--state-dir", type=Path,
                        default=home / ".local/state/omarchy/current")
    parser.add_argument("--config", type=Path, default=None,
                        help="TOML config (default: $XDG_CONFIG_HOME/omarchy-apps/theme.toml)")
    parser.add_argument("--check", "--dry-run", action="store_true",
                        help="validate ownership/input and report changes without writing")
    parser.add_argument("--quiet", action="store_true", help="suppress success output")
    args = parser.parse_args(argv)
    try:
        config_path = args.config or config_home / "omarchy-apps/theme.toml"
        config = {}
        if args.config is not None or config_path.exists():
            with config_path.open("rb") as stream:
                config = tomllib.load(stream)
        with args.source.open(encoding="utf-8") as stream:
            rendered = render(json.load(stream), config)
        changed = sync(args.state_dir, rendered, args.check)
    except (OSError, ValueError) as exc:
        print(f"omarchy theme bridge: {exc}", file=sys.stderr)
        return 1
    if not args.quiet:
        action = "Would update" if args.check else "Updated"
        print(f"{action}: {', '.join(changed)}" if changed else "Theme already up to date")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
